flowchart LR
    rpki_archive[RPKI Archives]
    vrp_diff[rpkilog vrp_diff]
    s3_rpkilog_diff[(aws s3<br>rpkilog-diff bucket)]
    es[(ElasticSearch)]
    www_ui[WWW User Interface]
    diff_notifier[Diff Notification Tool]
    notification_queue[Queue]
    notification_asn_map[(Notification<br>ASN Subscriptions)]
    notification_prefix_map[(Notification<br>Prefix<br>Subscriptions)]
    notification_subscribers[(Notification<br>Subscribers)]
    notification_email_sender[Email sender]

    rpki_archive-->vrp_diff
    vrp_diff-->s3_rpkilog_diff
    
    s3_rpkilog_diff-->es
    es-->www_ui

    s3_rpkilog_diff-->diff_notifier
    notification_asn_map-->diff_notifier
    notification_prefix_map-->diff_notifier
    diff_notifier-->notification_queue
    notification_queue-->notification_email_sender
    notification_subscribers-->notification_email_sender
