#cloud-config
apt:
  sources:
    docker.list:
      source: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable"
      keyid: 7EA0A9C3F273FCD8
disk_setup:
  /dev/sdb:
    layout: true
    overwrite: false
    table_type: gpt
# At least once, Incus reversed the order of disks; the 20GB data disk became sda (wrong) and the OS
# disk became sdb.  This caused a malfunction as sdb1, which was mounted at /data, was a vfat filesystem
# meant for EFI/UEFI booting, and the below filesystem wasn't created.
# If it happens again we will need to figure out how to fix it.  :/
fs_setup:
  - device: /dev/sdb1
    # ext4 defaults to one inode per 16KB disk space.  Create this filesystem with inode per 4KB.
    extra_opts:
      - -i 4096
    filesystem: ext4
    label: rpkiclient-2-dat  # length limitation
    overwrite: false
mounts:
  - [/dev/sdb1, /data]
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - docker-ce
  - docker-ce-cli
  - htop
  - incus-agent
  - openssh-server
  - ssh-import-id
users:
  - name: jsw
    groups: adm,docker,sudo
    shell: /usr/bin/bash
    sudo: "ALL=(ALL) NOPASSWD: ALL"
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4k8nVaS9Ns+8jZ1C97eUcOvkFw6NOXS8e4xxG6XEH1l9PDluOCxAqgCvdKxX9ZhFvwW1SCSWuN95WrM7u/9p0flOX7DZFYld053ClWxMZZ4ZtKj8XWnmDU4LLXSmUWaKddW9pHZHvxfEFu+wCcnUiJM4NgS4owfaIGC3IOIXVrxsoNuoKyTQS9pRa5+3sMC3rHK8oWPkleJGO+cs8AxuetRtHS/ZHwshsyI27ROC/nIxZ7ZeKXf3g/jxEpbxI9LNFnocuUmeoNpndBFYND1ujwiHZvoWxx4ByiTRDNJDHJWdnJpz8rOmnoHeHFqV8F/I5CRG9Dh7aq5vd9LWdrkqb jeffsw6@gmail.com boomer 2013-05-28
write_files:
  - path: /var/lib/cloud/scripts/per-once/100-rpki-client.sh
    permissions: "0755"
    content: |
        #!/bin/bash

        # rpki-client container from https://hub.docker.com/r/rpki/rpki-client
        docker run --name rpkiclient \
          --restart unless-stopped \
          --volume /data/rpkiclient/cache:/var/cache/rpki-client \
          --volume /data/rpkiclient/output:/var/lib/rpki-client \
          --publish 9099:9099/tcp \
          --detach \
          rpki/rpki-client:latest
